/**
 * Overview home (`#/`) — the D-06 landing view. Renders real headline
 * stats, recent PRs, and recent activities sourced from data already
 * published by `copyDataFiles()` — no new pipeline work.
 *
 * The large per-effort records file (2.5MB, under `data/stats/`) is never
 * fetched from the browser; "Recent PRs" derives from `row.prCount`,
 * already resolved at build time by the Phase 15 generator.
 */

import type { DashboardView, ViewMountContext } from '../view.types.js';
import { ROUTES } from '../view.types.js';
import type { IndexClient, FetchLike } from '../data/index-client.js';
import type { DashboardIndexRow } from '../../analytics/dashboard-index.types.js';
import { renderActivityRow, formatActivityDate } from './list.js';
import { activityDetailHref } from '../row-navigation.js';

const RECENT_PR_COUNT = 5;
const RECENT_ACTIVITY_COUNT = 10;
const STATS_BASE_URL = 'data/stats/';

/** Live shape of `data/stats/all-time-totals.json` (compute-stats.ts). */
interface AllTimeTotals {
  totalKm: number;
  totalRuns: number;
  totalHours: number;
  totalElevation: number;
  avgPaceMinPerKm: number;
  firstActivityDate: string;
  lastActivityDate: string;
  generatedAt: string;
}

/** Live shape of `data/stats/streaks.json` (streak-utils.ts). */
interface StreaksStats {
  currentStreak: number;
  longestStreak: number;
  withinCurrentStreak: boolean;
  currentStreakStart: string | null;
  longestStreakStart: string | null;
  longestStreakEnd: string | null;
  weeklyConsistency: unknown;
}

function buildStatCard(value: string, label: string): HTMLElement {
  const wrapper = document.createElement('div');
  const valueEl = document.createElement('div');
  valueEl.className = 'text-display';
  valueEl.textContent = value;
  const labelEl = document.createElement('div');
  labelEl.className = 'text-label';
  labelEl.textContent = label;
  wrapper.appendChild(valueEl);
  wrapper.appendChild(labelEl);
  return wrapper;
}

/**
 * Fetches and parses a small stats JSON file, using the same non-ok error
 * shape as the data clients. Individually try/catch-guarded by the caller
 * so a missing stats file (gitignored, regenerated by a compute run) never
 * fails the whole view — it degrades to an em-dash placeholder card
 * instead.
 */
async function fetchStatsJson<T>(url: string, doFetch: FetchLike): Promise<T | null> {
  try {
    const response = await doFetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch data: ${response.status} ${response.statusText}`);
    }
    return (await response.json()) as T;
  } catch (error) {
    console.error(error);
    return null;
  }
}

/**
 * A lighter-weight recent-PR row: name, local date, distance, and a
 * PR-count badge — not the full `renderActivityRow`.
 *
 * This row is now a whole-row `<a>` (D-08). Its three children — the name
 * div, the meta div, the PR-count badge — are deliberately unchanged in
 * this edit: Phase 20 owns the row's link semantic, Phase 21
 * (OVR-01/OVR-02) owns the row's contents, following Phase 19's D-14
 * precedent. `row.name` continues to reach the DOM only through
 * `textContent`, never an HTML-string assignment.
 */
function renderRecentPrRow(row: DashboardIndexRow): HTMLElement {
  const rowEl = document.createElement('a');
  rowEl.className = 'activity-row';
  const distanceKm = (row.distanceM / 1000).toFixed(1);
  rowEl.href = activityDetailHref(row.id);
  rowEl.setAttribute(
    'aria-label',
    `${row.name}, ${formatActivityDate(row.startDateLocal)}, ${distanceKm} km`
  );

  const nameEl = document.createElement('div');
  nameEl.className = 'activity-row__name';
  nameEl.textContent = row.name;
  rowEl.appendChild(nameEl);

  const metaEl = document.createElement('div');
  metaEl.className = 'activity-row__meta';
  metaEl.textContent = `${formatActivityDate(row.startDateLocal)} · ${distanceKm} km`;
  rowEl.appendChild(metaEl);

  const badge = document.createElement('span');
  badge.className = 'badge';
  badge.textContent = `${row.prCount} PR`;
  rowEl.appendChild(badge);

  return rowEl;
}

function buildHeadlineStatsCard(totals: AllTimeTotals | null, streaks: StreaksStats | null): HTMLElement {
  const section = document.createElement('section');
  section.className = 'card';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.textContent = 'Headline Stats';
  section.appendChild(heading);

  const grid = document.createElement('div');
  grid.className = 'stat-grid';
  grid.appendChild(buildStatCard(totals ? `${totals.totalKm.toFixed(1)} km` : '—', 'Total Distance'));
  grid.appendChild(buildStatCard(totals ? String(totals.totalRuns) : '—', 'Total Runs'));
  grid.appendChild(buildStatCard(totals ? String(Math.round(totals.totalHours)) : '—', 'Total Hours'));
  grid.appendChild(
    buildStatCard(totals ? `${Math.round(totals.totalElevation)} m` : '—', 'Total Elevation')
  );
  grid.appendChild(buildStatCard(streaks ? `${streaks.currentStreak} days` : '—', 'Current Streak'));
  grid.appendChild(buildStatCard(streaks ? `${streaks.longestStreak} days` : '—', 'Longest Streak'));
  section.appendChild(grid);

  return section;
}

function buildRecentPrsCard(rows: DashboardIndexRow[]): HTMLElement {
  const section = document.createElement('section');
  section.className = 'card';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.textContent = 'Recent PRs';
  section.appendChild(heading);

  const recentPrs = rows.filter((row) => row.prCount > 0).slice(0, RECENT_PR_COUNT);

  if (recentPrs.length === 0) {
    const empty = document.createElement('p');
    empty.className = 'text-body';
    empty.textContent = 'No personal records in the archive yet.';
    section.appendChild(empty);
  } else {
    const listEl = document.createElement('div');
    listEl.className = 'activity-list';
    for (const row of recentPrs) {
      listEl.appendChild(renderRecentPrRow(row));
    }
    section.appendChild(listEl);
  }

  return section;
}

function buildRecentActivitiesCard(rows: DashboardIndexRow[]): HTMLElement {
  const section = document.createElement('section');
  section.className = 'card';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.textContent = 'Recent Activities';
  section.appendChild(heading);

  const listEl = document.createElement('div');
  listEl.className = 'activity-list';
  for (const row of rows.slice(0, RECENT_ACTIVITY_COUNT)) {
    listEl.appendChild(renderActivityRow(row));
  }
  section.appendChild(listEl);

  return section;
}

export interface OverviewViewDeps {
  indexClient: IndexClient;
  fetchImpl?: FetchLike;
}

export function createOverviewView(deps: OverviewViewDeps): DashboardView {
  const { indexClient } = deps;
  let mountedContainer: HTMLElement | null = null;

  return {
    route: ROUTES.OVERVIEW,
    title: 'Overview',

    async mount(ctx: ViewMountContext): Promise<void> {
      mountedContainer = ctx.container;
      ctx.container.replaceChildren();

      const loading = document.createElement('div');
      loading.className = 'loading-indicator';
      loading.setAttribute('role', 'status');
      loading.textContent = 'Loading overview…';
      ctx.container.appendChild(loading);

      const doFetch = deps.fetchImpl ?? (globalThis.fetch as unknown as FetchLike);

      let totals: AllTimeTotals | null;
      let streaks: StreaksStats | null;
      try {
        [, totals, streaks] = await Promise.all([
          indexClient.loadIndex(),
          fetchStatsJson<AllTimeTotals>(`${STATS_BASE_URL}all-time-totals.json`, doFetch),
          fetchStatsJson<StreaksStats>(`${STATS_BASE_URL}streaks.json`, doFetch),
        ]);
      } catch (error) {
        console.error(error);
        // A rejection can arrive after the user navigated away — must not
        // wipe the newly-mounted view (WR-01).
        if (mountedContainer !== ctx.container) {
          return;
        }
        ctx.container.replaceChildren();
        const errorState = document.createElement('section');
        errorState.className = 'error-state';
        const heading = document.createElement('h2');
        heading.className = 'text-heading';
        heading.textContent = "Couldn't load the overview";
        const body = document.createElement('p');
        body.className = 'text-body';
        body.textContent = 'Check your connection and try again.';
        errorState.appendChild(heading);
        errorState.appendChild(body);
        ctx.container.appendChild(errorState);
        return;
      }

      // mount() may resolve after the view was unmounted (fast navigation
      // away before the index/stats finished loading).
      if (mountedContainer !== ctx.container) {
        return;
      }

      ctx.container.replaceChildren();

      const view = document.createElement('div');
      view.className = 'view';

      const heading = document.createElement('h1');
      heading.className = 'text-heading';
      heading.textContent = 'Overview';
      heading.setAttribute('tabindex', '-1');
      view.appendChild(heading);

      const rows = indexClient.getRows();

      view.appendChild(buildHeadlineStatsCard(totals, streaks));
      view.appendChild(buildRecentPrsCard(rows));
      view.appendChild(buildRecentActivitiesCard(rows));

      ctx.container.appendChild(view);

      // Every hash navigation announces a context change to assistive tech
      // (17-UI-SPEC § 5 Cross-Surface focus management) — overview is the
      // only view no other Phase 17 plan touches.
      heading.focus();
    },

    unmount(): void {
      mountedContainer?.replaceChildren();
      mountedContainer = null;
    },
  };
}
