/**
 * Records page (`#/records`) — REC-02/03/05/06/07, 18-UI-SPEC. Replaces the
 * Phase 16 stub with a sticky jump list, four superlative tiles, seven
 * per-distance PR tables (age-grade + honesty badges), a seven-card PR
 * evolution grid, and a Race Predictions section.
 *
 * Every number on this page comes from plan 18-09's tested, DOM-free
 * `records-logic.ts`/`riegel.ts` functions — this module is DOM assembly
 * only, mirroring `overview.ts`'s degrade-to-null fetch idiom and
 * `calendar.ts`'s single `mountedContainer !== ctx.container` stale-render
 * guard (Records has no per-parameter navigation race, so `detail.ts`'s
 * heavier `requestToken` machinery is not needed here).
 *
 * The evolution grid's seven Chart.js instances live behind a lazy
 * `await import('./records-charts.js')` (D-25's lazy-chunk-boundary
 * discipline) — this module's own static import graph never pulls in
 * Chart.js.
 */

import type { DashboardView, ViewMountContext } from '../view.types.js';
import { ROUTES, NAV_ORDER } from '../view.types.js';
import type { IndexClient, FetchLike } from '../data/index-client.js';
import type { BestEffortsDocument, TargetDistanceKey } from '../../analytics/best-effort.types.js';
import { TARGET_ORDER } from '../../analytics/best-effort.types.js';
import type { AgeGradingDocument } from '../../analytics/age-grading.types.js';
import {
  buildExclusionReasonIndex,
  buildPrTableRows,
  isEmptyRanking,
  buildEvolutionSeries,
  buildProgressionRows,
  selectSuperlatives,
  evolutionCardSummary,
  type PrTableRow,
  type EvolutionPoint,
  type Superlatives,
} from './records-logic.js';
import { buildRiegelMatrix, fitRiegelExponent, selectFitPoints } from '../../analytics/riegel.js';
import {
  formatActivityDate,
  formatPace,
  formatEffortDuration,
  appendBadge,
  appendLowConfidenceBadge,
} from './list.js';
import { attachRowNavigation, activityDetailHref } from '../row-navigation.js';

const STATS_BASE_URL = 'data/stats/';
const EXCLUSIONS_URL = 'data/best-effort-exclusions.json';

// ---------------------------------------------------------------------------
// records-charts.ts lazy-module type aliases (D-25 pattern, mirroring
// detail.ts's own `typeof import(...)` aliases). A type-only query erases
// completely at compile time and produces no runtime import, so declaring
// these does NOT pull records-charts.ts (and therefore Chart.js) into this
// file's static import graph. The actual VALUE import happens only inside
// `mountCharts` below, via `await import(...)`.
// ---------------------------------------------------------------------------
type RecordsChartsModule = typeof import('./records-charts.js');
type EvolutionChartsHandle = ReturnType<RecordsChartsModule['mountEvolutionCharts']>;
type EvolutionChartCard = Parameters<RecordsChartsModule['mountEvolutionCharts']>[0][number];

type RiegelMatrix = ReturnType<typeof buildRiegelMatrix>;

const DISTANCE_LABELS: Record<TargetDistanceKey, string> = {
  '400m': '400m',
  '1k': '1K',
  '1mi': '1 Mile',
  '5k': '5K',
  '10k': '10K',
  half: 'Half Marathon',
  marathon: 'Marathon',
};

/** `TargetDistanceKey`'s own values (`1mi`) differ from the id slug UI-SPEC asks for (`1mile`). */
const DISTANCE_SLUGS: Record<TargetDistanceKey, string> = {
  '400m': '400m',
  '1k': '1k',
  '1mi': '1mile',
  '5k': '5k',
  '10k': '10k',
  half: 'half',
  marathon: 'marathon',
};

const RECORDS_NAV_ENTRY = NAV_ORDER.find((entry) => entry.route === ROUTES.RECORDS);

/**
 * Fetches and parses a small stats JSON file, using the same non-ok error
 * shape as the data clients. Individually degrade-guarded so a missing
 * stats file (gitignored, regenerated by a compute run) never fails the
 * whole view — it degrades to `null`, which each section renders as its own
 * named absence rather than throwing (mirrors `overview.ts`'s idiom).
 */
async function fetchStatsJson<T>(url: string, doFetch: FetchLike): Promise<T | null> {
  try {
    const response = await doFetch(url);
    if (!response.ok) {
      throw new Error(`Failed to fetch data: ${response.status} ${response.statusText}`);
    }
    return (await response.json()) as T;
  } catch (error) {
    console.error(error);
    return null;
  }
}

// ---------------------------------------------------------------------------
// Error state — the exact three-part formula (heading + body + Retry),
// copied character-for-character from 18-UI-SPEC's Copywriting Contract.
// ---------------------------------------------------------------------------

function renderErrorState(container: HTMLElement, onRetry: () => void): void {
  container.replaceChildren();

  const errorState = document.createElement('section');
  errorState.className = 'error-state';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.textContent = "Couldn't load records";
  errorState.appendChild(heading);

  const body = document.createElement('p');
  body.className = 'text-body';
  body.textContent = 'Check your connection and try again.';
  errorState.appendChild(body);

  const retryBtn = document.createElement('button');
  retryBtn.type = 'button';
  retryBtn.className = 'cta';
  retryBtn.textContent = 'Retry';
  retryBtn.addEventListener('click', onRetry);
  errorState.appendChild(retryBtn);

  container.appendChild(errorState);
}

// ---------------------------------------------------------------------------
// Sticky jump list (18-UI-SPEC § 1) — buttons + scrollIntoView only, never a
// real same-page hash anchor (the hash-router-collision landmine: a rewritten
// location.hash would be parsed by router.ts as an unknown route).
// ---------------------------------------------------------------------------

interface JumpTarget {
  section: HTMLElement;
  heading: HTMLElement;
  label: string;
}

function buildJumpList(items: readonly JumpTarget[]): { nav: HTMLElement; buttons: HTMLButtonElement[] } {
  const nav = document.createElement('nav');
  nav.className = 'records-jump';
  nav.setAttribute('aria-label', 'Records sections');

  const buttons: HTMLButtonElement[] = [];
  for (const item of items) {
    const btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'records-jump__link';
    btn.textContent = item.label;
    btn.addEventListener('click', () => {
      item.section.scrollIntoView({ behavior: 'smooth', block: 'start' });
      item.heading.focus();
    });
    nav.appendChild(btn);
    buttons.push(btn);
  }

  return { nav, buttons };
}

/**
 * Sets the jump list's sticky offset from the LIVE `.app-nav` element's
 * rendered height — never a hardcoded pixel value, since the nav's own
 * height changes shape at the 640px breakpoint (link row vs. hamburger row).
 */
function updateJumpOffset(nav: HTMLElement): void {
  const appNavEl = document.querySelector('.app-nav');
  const height = appNavEl instanceof HTMLElement ? appNavEl.getBoundingClientRect().height : 0;
  nav.style.top = `${height}px`;
}

/**
 * Watches the four top-level sections and marks the currently-intersecting
 * one's jump button `aria-current="location"` — the ARIA APG token for an
 * in-page table of contents, distinct from `nav.ts`'s `aria-current="page"`.
 */
function wireActiveSectionObserver(
  pairs: readonly { section: HTMLElement; button: HTMLButtonElement }[]
): IntersectionObserver {
  const observer = new IntersectionObserver(
    (entries) => {
      for (const entry of entries) {
        if (!entry.isIntersecting) continue;
        const pair = pairs.find((p) => p.section === entry.target);
        if (!pair) continue;
        for (const p of pairs) p.button.removeAttribute('aria-current');
        pair.button.setAttribute('aria-current', 'location');
      }
    },
    { rootMargin: '-10% 0px -80% 0px', threshold: 0 }
  );
  for (const pair of pairs) observer.observe(pair.section);
  return observer;
}

// ---------------------------------------------------------------------------
// Superlatives (18-UI-SPEC § 4a)
// ---------------------------------------------------------------------------

/**
 * Builds one tile: value (`.text-display`) + category label + an optional
 * context sub-label — two `.text-label` lines rather than one, reusing the
 * existing role twice (zero new CSS) so the tile still names its own
 * category even though `overview.ts`'s `buildStatCard` anatomy only ever
 * needed a single label line.
 */
function buildSuperlativeTile(value: string, label: string, sublabel?: string): HTMLElement {
  const wrapper = document.createElement('div');

  const valueEl = document.createElement('div');
  valueEl.className = 'text-display';
  valueEl.textContent = value;
  wrapper.appendChild(valueEl);

  const labelEl = document.createElement('div');
  labelEl.className = 'text-label';
  labelEl.textContent = label;
  wrapper.appendChild(labelEl);

  if (sublabel) {
    const subEl = document.createElement('div');
    subEl.className = 'text-label';
    subEl.textContent = sublabel;
    wrapper.appendChild(subEl);
  }

  return wrapper;
}

function buildSuperlativesSection(superlatives: Superlatives): HTMLElement {
  const section = document.createElement('section');
  section.id = 'records-superlatives';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.tabIndex = -1;
  heading.textContent = 'Superlatives';
  section.appendChild(heading);

  const card = document.createElement('div');
  card.className = 'card detail-section';

  const grid = document.createElement('div');
  grid.className = 'stat-grid';

  const { biggestWeek, biggestMonth, longestStreak, currentStreak } = superlatives;

  grid.appendChild(
    buildSuperlativeTile(
      biggestWeek ? `${biggestWeek.km.toFixed(1)} km` : '—',
      'Biggest Week',
      biggestWeek ? `week of ${formatActivityDate(biggestWeek.weekStartISO)}` : undefined
    )
  );
  grid.appendChild(
    buildSuperlativeTile(
      biggestMonth ? `${biggestMonth.km.toFixed(1)} km` : '—',
      'Biggest Month',
      biggestMonth ? biggestMonth.label : undefined
    )
  );
  grid.appendChild(
    buildSuperlativeTile(
      longestStreak ? `${longestStreak.days} days` : '—',
      'Longest Streak',
      longestStreak
        ? `${formatActivityDate(longestStreak.startISO)} – ${formatActivityDate(longestStreak.endISO)}`
        : undefined
    )
  );
  // A `0`-day current streak is a real value (T-18-HONEST-05) — the tile
  // only falls back to an em-dash when the whole `currentStreak` OBJECT is
  // absent, never because `days` happens to be zero.
  grid.appendChild(
    buildSuperlativeTile(
      currentStreak ? `${currentStreak.days} days` : '—',
      'Current Streak',
      currentStreak
        ? currentStreak.active
          ? 'active'
          : currentStreak.endedISO
            ? `ended ${formatActivityDate(currentStreak.endedISO)}`
            : undefined
        : undefined
    )
  );

  card.appendChild(grid);
  section.appendChild(card);
  return section;
}

// ---------------------------------------------------------------------------
// PR tables (18-UI-SPEC § 2)
// ---------------------------------------------------------------------------

function buildConfigNotice(ageGrading: AgeGradingDocument | null): HTMLElement | null {
  if (ageGrading && ageGrading.enabled) return null;
  const notice = document.createElement('div');
  notice.className = 'config-notice';
  notice.textContent =
    ageGrading?.disabledReason ??
    'Age-grading is off — add birthDate and sex to data/private/athlete-private.json to enable it.';
  return notice;
}

function buildPrTableEmptyState(): HTMLElement {
  const empty = document.createElement('div');
  empty.className = 'empty-state';

  const heading = document.createElement('h3');
  heading.className = 'text-heading';
  heading.textContent = 'No marathon efforts yet';
  empty.appendChild(heading);

  const body = document.createElement('p');
  body.className = 'text-body';
  body.textContent =
    'The archive has no completed marathon-distance run. Once one is recorded, its rank will appear here.';
  empty.appendChild(body);

  return empty;
}

/**
 * Renders one distance's PR table. Every row is a single navigable
 * affordance (REC-08, UX-02): the Date cell carries the real anchor
 * because `PrTableRow` has no activity-name field to anchor instead
 * (D-05 explicitly defers joining one in — that is Phase 21-shaped work),
 * and `attachRowNavigation` adds the row-level click/mouse path on top,
 * guarded so the two never double-navigate (D-03). The `<tr>` itself
 * deliberately carries no `tabindex` and no `role="link"` — the keyboard
 * path is the Date-cell anchor alone (D-01). The former "View Activity"
 * column is gone under UX-02: the row itself is now the affordance.
 */
function buildPrTable(distance: TargetDistanceKey, rows: readonly PrTableRow[]): HTMLElement {
  const table = document.createElement('table');
  table.className = 'activity-table pr-table';

  const thead = document.createElement('thead');
  const headRow = document.createElement('tr');
  const headers: { label: string; numeric: boolean }[] = [
    { label: 'Rank', numeric: true },
    { label: 'Time', numeric: true },
    { label: 'Pace', numeric: true },
    { label: 'Age-Grade', numeric: true },
    { label: 'Date', numeric: false },
    { label: 'Flags', numeric: false },
  ];
  for (const header of headers) {
    const th = document.createElement('th');
    th.textContent = header.label;
    if (header.numeric) th.className = 'pr-table__numeric';
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);

  const tbody = document.createElement('tbody');
  for (const row of rows) {
    const tr = document.createElement('tr');

    const rankTd = document.createElement('td');
    rankTd.className = 'pr-table__numeric';
    rankTd.textContent = `#${row.rank}`;
    tr.appendChild(rankTd);

    const timeTd = document.createElement('td');
    timeTd.className = 'pr-table__numeric';
    timeTd.textContent = formatEffortDuration(row.durationSec);
    tr.appendChild(timeTd);

    const paceTd = document.createElement('td');
    paceTd.className = 'pr-table__numeric';
    paceTd.textContent = formatPace(row.paceSecPerKm);
    tr.appendChild(paceTd);

    const ageTd = document.createElement('td');
    ageTd.className = 'pr-table__numeric';
    ageTd.textContent =
      row.agePercent !== null ? `${row.agePercent.toFixed(1)}%${row.ageDerived ? '*' : ''}` : '—';
    tr.appendChild(ageTd);

    const dateTd = document.createElement('td');
    const dateAnchor = document.createElement('a');
    dateAnchor.href = activityDetailHref(row.activityId);
    dateAnchor.textContent = formatActivityDate(row.startDate);
    // Curated label built only from fields PrTableRow carries (D-04):
    // PrTableRow has no activity name (D-05 defers joining one in), so
    // this deliberately differs from list.ts's name-first template.
    dateAnchor.setAttribute(
      'aria-label',
      `${formatActivityDate(row.startDate)}, ${DISTANCE_LABELS[distance]}, ${formatEffortDuration(row.durationSec)}`
    );
    dateTd.appendChild(dateAnchor);
    tr.appendChild(dateTd);

    const flagsTd = document.createElement('td');
    if (row.lowConfidence) {
      appendLowConfidenceBadge(flagsTd, `pr-${distance}-${row.activityId}`);
    }
    if (row.excluded && row.exclusionReason) {
      appendBadge(flagsTd, `Excluded — ${row.exclusionReason}`);
    }
    tr.appendChild(flagsTd);

    attachRowNavigation(tr, row.activityId);
    tbody.appendChild(tr);
  }
  table.appendChild(tbody);

  return table;
}

function buildPrTableSection(distance: TargetDistanceKey, rows: readonly PrTableRow[], empty: boolean): HTMLElement {
  const section = document.createElement('section');
  section.className = 'card detail-section';
  section.id = `pr-table-${DISTANCE_SLUGS[distance]}`;

  const heading = document.createElement('h3');
  heading.className = 'text-heading';
  heading.textContent = DISTANCE_LABELS[distance];
  section.appendChild(heading);

  if (empty) {
    section.appendChild(buildPrTableEmptyState());
    return section;
  }

  section.appendChild(buildPrTable(distance, rows));

  if (distance === '1k') {
    const footnote = document.createElement('p');
    footnote.className = 'text-label';
    footnote.textContent =
      '* Interpolated between 800m and mile factors — no official WMA standard exists for 1k.';
    section.appendChild(footnote);
  }

  return section;
}

function buildPrTablesSection(
  bestEfforts: BestEffortsDocument,
  ageGrading: AgeGradingDocument | null,
  exclusionReasons: ReadonlyMap<string, string>
): HTMLElement {
  const section = document.createElement('section');
  section.id = 'records-pr-tables';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.tabIndex = -1;
  heading.textContent = 'PR Tables';
  section.appendChild(heading);

  const notice = buildConfigNotice(ageGrading);
  if (notice) section.appendChild(notice);

  for (const distance of TARGET_ORDER) {
    const entries = bestEfforts.rankings[distance];
    const empty = isEmptyRanking(entries);
    const rows = buildPrTableRows(entries, ageGrading, distance, exclusionReasons);
    section.appendChild(buildPrTableSection(distance, rows, empty));
  }

  return section;
}

// ---------------------------------------------------------------------------
// PR evolution grid (18-UI-SPEC § 3)
// ---------------------------------------------------------------------------

function buildProgressionTable(series: readonly EvolutionPoint[]): HTMLElement {
  const table = document.createElement('table');
  table.className = 'activity-table pr-table';

  const thead = document.createElement('thead');
  const headRow = document.createElement('tr');
  for (const label of ['Date', 'Time', 'Improvement', 'Run']) {
    const th = document.createElement('th');
    th.textContent = label;
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);

  const tbody = document.createElement('tbody');
  for (const row of buildProgressionRows(series)) {
    const tr = document.createElement('tr');

    const dateTd = document.createElement('td');
    dateTd.textContent = formatActivityDate(row.startDate);
    tr.appendChild(dateTd);

    const timeTd = document.createElement('td');
    timeTd.textContent = formatEffortDuration(row.durationSec);
    tr.appendChild(timeTd);

    const improvementTd = document.createElement('td');
    improvementTd.textContent =
      row.improvementSec === null ? '—' : `−${formatEffortDuration(Math.abs(row.improvementSec))}`;
    tr.appendChild(improvementTd);

    const runTd = document.createElement('td');
    const cta = document.createElement('a');
    cta.className = 'cta';
    cta.textContent = 'View Activity';
    cta.href = `#/activity/${row.activityId}`;
    runTd.appendChild(cta);
    tr.appendChild(runTd);

    tbody.appendChild(tr);
  }
  table.appendChild(tbody);

  return table;
}

/**
 * Builds one evolution card. A distance with an empty series (marathon
 * today) renders its heading, an em-dash value, and a named "no PR history"
 * label — never a blank card, and no `<canvas>`/`<details>` at all, so the
 * caller never hands an empty series to `mountEvolutionCharts`.
 */
function buildEvolutionCard(
  distance: TargetDistanceKey,
  series: readonly EvolutionPoint[]
): { card: HTMLElement; canvas: HTMLCanvasElement | null } {
  const card = document.createElement('div');
  card.className = 'pr-evolution-card card';

  const heading = document.createElement('h3');
  heading.className = 'text-heading';
  heading.textContent = DISTANCE_LABELS[distance];
  card.appendChild(heading);

  const summary = evolutionCardSummary(series);

  const valueEl = document.createElement('div');
  valueEl.className = 'text-display';
  valueEl.textContent = summary.currentSec !== null ? formatEffortDuration(summary.currentSec) : '—';
  card.appendChild(valueEl);

  const labelEl = document.createElement('div');
  labelEl.className = 'text-label';
  labelEl.textContent =
    summary.steps > 0 ? `${summary.steps} steps, ${summary.firstYear}–${summary.lastYear}` : 'No PR history yet';
  card.appendChild(labelEl);

  if (series.length === 0) {
    return { card, canvas: null };
  }

  const canvasWrap = document.createElement('div');
  canvasWrap.className = 'pr-evolution-card__canvas-wrap';
  const canvas = document.createElement('canvas');
  canvasWrap.appendChild(canvas);
  card.appendChild(canvasWrap);

  const details = document.createElement('details');
  details.className = 'pr-evolution-card__details';
  const summaryEl = document.createElement('summary');
  summaryEl.textContent = `Show progression (${series.length} steps)`;
  details.appendChild(summaryEl);
  details.appendChild(buildProgressionTable(series));
  card.appendChild(details);

  return { card, canvas };
}

function buildEvolutionSection(activities: BestEffortsDocument['activities']): {
  section: HTMLElement;
  heading: HTMLElement;
  chartCards: EvolutionChartCard[];
} {
  const section = document.createElement('section');
  section.id = 'records-pr-evolution';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.tabIndex = -1;
  heading.textContent = 'PR Evolution';
  section.appendChild(heading);

  const grid = document.createElement('div');
  grid.className = 'pr-evolution-grid';

  const chartCards: EvolutionChartCard[] = [];

  for (const distance of TARGET_ORDER) {
    const series = buildEvolutionSeries(activities, distance);
    const { card, canvas } = buildEvolutionCard(distance, series);
    grid.appendChild(card);
    if (canvas) {
      chartCards.push({ distance, displayName: DISTANCE_LABELS[distance], canvas, points: series });
    }
  }

  section.appendChild(grid);
  return { section, heading, chartCards };
}

// ---------------------------------------------------------------------------
// Race Predictions (18-UI-SPEC § 4b, D-11)
// ---------------------------------------------------------------------------

function buildRiegelTable(matrix: RiegelMatrix): HTMLElement {
  const table = document.createElement('table');
  table.className = 'activity-table pr-table';

  const thead = document.createElement('thead');
  const headRow = document.createElement('tr');
  const corner = document.createElement('th');
  corner.textContent = 'From \\ To';
  headRow.appendChild(corner);
  for (const column of matrix.columns) {
    const th = document.createElement('th');
    th.className = 'pr-table__numeric';
    th.textContent = DISTANCE_LABELS[column];
    headRow.appendChild(th);
  }
  thead.appendChild(headRow);
  table.appendChild(thead);

  const tbody = document.createElement('tbody');
  matrix.rows.forEach((fromDistance, rowIndex) => {
    const tr = document.createElement('tr');

    const rowHeader = document.createElement('th');
    rowHeader.textContent = DISTANCE_LABELS[fromDistance];
    tr.appendChild(rowHeader);

    for (const cell of matrix.cells[rowIndex]) {
      const td = document.createElement('td');
      td.className = 'pr-table__numeric';
      td.textContent = `${formatEffortDuration(cell.predictedSec)} `;
      if (cell.isActual) {
        const em = document.createElement('em');
        em.textContent = '(actual)';
        td.appendChild(em);
      }
      tr.appendChild(td);
    }

    tbody.appendChild(tr);
  });
  table.appendChild(tbody);

  return table;
}

function buildPredictionsSection(bestEfforts: BestEffortsDocument): { section: HTMLElement; heading: HTMLElement } {
  const section = document.createElement('section');
  section.id = 'records-predictions';

  const heading = document.createElement('h2');
  heading.className = 'text-heading';
  heading.tabIndex = -1;
  heading.textContent = 'Race Predictions';
  section.appendChild(heading);

  const card = document.createElement('div');
  card.className = 'card detail-section';

  const rankings = bestEfforts.rankings;

  const standardLabel = document.createElement('p');
  standardLabel.className = 'text-label';
  standardLabel.textContent = 'Standard (b = 1.06)';
  card.appendChild(standardLabel);

  if (isEmptyRanking(rankings.marathon)) {
    const marathonNote = document.createElement('p');
    marathonNote.className = 'text-body';
    marathonNote.textContent =
      'No marathon has been run yet — this row is a Riegel-based estimate, not a recorded time.';
    card.appendChild(marathonNote);
  }

  card.appendChild(buildRiegelTable(buildRiegelMatrix(rankings)));

  const fitPoints = selectFitPoints(rankings);
  const fit = fitRiegelExponent(fitPoints);

  if (fit) {
    const fittedLabel = document.createElement('p');
    fittedLabel.className = 'text-label';
    const distanceNames = fit.distances.map((d) => DISTANCE_LABELS[d]).join(', ');
    fittedLabel.textContent = `Fitted exponent: b = ${fit.b.toFixed(3)} (from ${distanceNames}) — using rank-1 PRs only.`;
    card.appendChild(fittedLabel);

    card.appendChild(buildRiegelTable(buildRiegelMatrix(rankings, fit.b)));
  } else {
    const distinctCount = new Set(fitPoints.map((p) => p.activityId)).size;
    const suppression = document.createElement('p');
    suppression.className = 'text-body';
    suppression.textContent = `A fitted personal exponent isn't shown yet — it needs PRs from at least 3 different runs (currently ${distinctCount}).`;
    card.appendChild(suppression);
  }

  section.appendChild(card);
  return { section, heading };
}

// ---------------------------------------------------------------------------
// View factory
// ---------------------------------------------------------------------------

export interface RecordsViewDeps {
  indexClient: IndexClient;
  fetchImpl?: FetchLike;
}

export function createRecordsView(deps: RecordsViewDeps): DashboardView {
  let mountedContainer: HTMLElement | null = null;
  let resizeListener: (() => void) | null = null;
  let sectionObserver: IntersectionObserver | null = null;
  let chartsHandle: EvolutionChartsHandle | null = null;

  function cleanupInteractive(): void {
    if (resizeListener) {
      window.removeEventListener('resize', resizeListener);
      resizeListener = null;
    }
    if (sectionObserver) {
      sectionObserver.disconnect();
      sectionObserver = null;
    }
    if (chartsHandle) {
      chartsHandle.destroy();
      chartsHandle = null;
    }
  }

  async function load(ctx: ViewMountContext): Promise<void> {
    cleanupInteractive();
    ctx.container.replaceChildren();

    const loading = document.createElement('div');
    loading.className = 'loading-indicator';
    loading.setAttribute('role', 'status');
    loading.textContent = 'Loading records…';
    ctx.container.appendChild(loading);

    const doFetch = deps.fetchImpl ?? (globalThis.fetch as unknown as FetchLike);

    const [bestEfforts, ageGrading, weekly, monthly, streaks, exclusionsRaw] = await Promise.all([
      fetchStatsJson<BestEffortsDocument>(`${STATS_BASE_URL}best-efforts.json`, doFetch),
      fetchStatsJson<AgeGradingDocument>(`${STATS_BASE_URL}age-grading.json`, doFetch),
      fetchStatsJson<unknown>(`${STATS_BASE_URL}weekly-distance.json`, doFetch),
      fetchStatsJson<unknown>(`${STATS_BASE_URL}monthly-stats.json`, doFetch),
      fetchStatsJson<unknown>(`${STATS_BASE_URL}streaks.json`, doFetch),
      fetchStatsJson<unknown>(EXCLUSIONS_URL, doFetch),
    ]);

    // mount() may resolve after the view was unmounted (fast navigation away
    // before the fetch finished) — never paint into a container this view no
    // longer owns.
    if (mountedContainer !== ctx.container) return;

    if (bestEfforts === null) {
      renderErrorState(ctx.container, () => {
        void load(ctx);
      });
      return;
    }

    ctx.container.replaceChildren();

    const view = document.createElement('div');
    view.className = 'view';

    const h1 = document.createElement('h1');
    h1.className = 'text-heading';
    h1.textContent = 'Records';
    h1.tabIndex = -1;
    view.appendChild(h1);

    const exclusionReasons = buildExclusionReasonIndex(exclusionsRaw);
    const superlatives = selectSuperlatives(weekly, monthly, streaks);

    const superlativesSection = buildSuperlativesSection(superlatives);
    const prTablesSection = buildPrTablesSection(bestEfforts, ageGrading, exclusionReasons);
    const evolution = buildEvolutionSection(bestEfforts.activities);
    const predictions = buildPredictionsSection(bestEfforts);

    const superlativesHeading = superlativesSection.querySelector('h2')!;
    const prTablesHeading = prTablesSection.querySelector('h2')!;

    const jumpTargets: JumpTarget[] = [
      { section: superlativesSection, heading: superlativesHeading, label: 'Superlatives' },
      { section: prTablesSection, heading: prTablesHeading, label: 'PR Tables' },
      { section: evolution.section, heading: evolution.heading, label: 'PR Evolution' },
      { section: predictions.section, heading: predictions.heading, label: 'Race Predictions' },
    ];

    const { nav, buttons } = buildJumpList(jumpTargets);

    view.appendChild(nav);
    view.appendChild(superlativesSection);
    view.appendChild(prTablesSection);
    view.appendChild(evolution.section);
    view.appendChild(predictions.section);

    ctx.container.appendChild(view);

    // Every hash navigation announces a context change to assistive tech
    // (17-UI-SPEC § 5 Cross-Surface focus management), same discipline as
    // every other Phase 16/17 view.
    h1.focus();

    updateJumpOffset(nav);
    const onResize = () => updateJumpOffset(nav);
    window.addEventListener('resize', onResize);
    resizeListener = onResize;

    sectionObserver = wireActiveSectionObserver(
      jumpTargets.map((target, i) => ({ section: target.section, button: buttons[i] }))
    );

    if (evolution.chartCards.length > 0) {
      const chartsModule = await import('./records-charts.js');
      if (mountedContainer !== ctx.container) return;
      chartsHandle = chartsModule.mountEvolutionCharts(evolution.chartCards);
    }
  }

  return {
    route: ROUTES.RECORDS,
    title: 'Records',
    navEntry: RECORDS_NAV_ENTRY,

    async mount(ctx: ViewMountContext): Promise<void> {
      mountedContainer = ctx.container;
      await load(ctx);
    },

    unmount(): void {
      cleanupInteractive();
      mountedContainer?.replaceChildren();
      mountedContainer = null;
    },
  };
}
