import fs from 'node:fs';

import { describe, expect, it } from 'vitest';

import {
  buildYoySeries,
  DEFAULT_YOY_YEAR_COUNT,
  defaultYoyYears,
  listYoyYears,
  parseYearOverYear,
  toggleYoyYear,
} from './trends-yoy-logic.js';

/**
 * Reads the derived, gitignored `data/stats/year-over-year.json` directly
 * via `node:fs` (relative to CWD, same convention as
 * `best-effort-fixtures.test.ts`) — regenerated by `npm run compute-all-stats`,
 * absent on a fresh clone until that pipeline runs.
 */
const yearOverYearLive: unknown = JSON.parse(fs.readFileSync('data/stats/year-over-year.json', 'utf-8'));

describe('parseYearOverYear — live data/stats/year-over-year.json', () => {
  it('returns 12 months', () => {
    const months = parseYearOverYear(yearOverYearLive);
    expect(months).toHaveLength(12);
  });
});

describe('parseYearOverYear — tolerant entry-level parsing', () => {
  it('drops a single malformed entry while the rest survive', () => {
    const raw = [
      { month: 1, monthLabel: 'Jan', years: { '2024': { totalKm: 10, totalRuns: 1, totalHours: 1 } } },
      { month: 2, monthLabel: 'Feb' }, // missing years — malformed
      { month: 3, monthLabel: 'Mar', years: { '2024': { totalKm: 20, totalRuns: 2, totalHours: 2 } } },
    ];
    const months = parseYearOverYear(raw);
    expect(months).toHaveLength(2);
    expect(months.map((m) => m.month)).toEqual([1, 3]);
  });

  it('null returns []', () => {
    expect(parseYearOverYear(null)).toEqual([]);
  });

  it('{} returns []', () => {
    expect(parseYearOverYear({})).toEqual([]);
  });

  it('[] returns []', () => {
    expect(parseYearOverYear([])).toEqual([]);
  });

  it('__proto__-keyed years is not reachable as Object.prototype', () => {
    const raw = [
      {
        month: 1,
        monthLabel: 'Jan',
        years: JSON.parse('{"__proto__": {"totalKm": 999, "totalRuns": 99, "totalHours": 9}}'),
      },
    ];
    const months = parseYearOverYear(raw);
    // The polluted key must not leak onto Object.prototype.
    expect(({} as Record<string, unknown>).totalKm).toBeUndefined();
    // And it must not surface as a usable "year" (Number('__proto__') is NaN).
    expect(listYoyYears(months)).toEqual([]);
  });
});

describe('listYoyYears', () => {
  it('ascending and distinct across months with differing year sets', () => {
    const months = parseYearOverYear([
      { month: 1, monthLabel: 'Jan', years: { '2024': { totalKm: 1, totalRuns: 1, totalHours: 1 } } },
      { month: 2, monthLabel: 'Feb', years: { '2025': { totalKm: 1, totalRuns: 1, totalHours: 1 }, '2023': { totalKm: 1, totalRuns: 1, totalHours: 1 } } },
    ]);
    expect(listYoyYears(months)).toEqual([2023, 2024, 2025]);
  });
});

describe('defaultYoyYears', () => {
  it('returns the 3 most recent years when >= 3 exist', () => {
    const months = parseYearOverYear([
      { month: 1, monthLabel: 'Jan', years: {
        '2022': { totalKm: 1, totalRuns: 1, totalHours: 1 },
        '2023': { totalKm: 1, totalRuns: 1, totalHours: 1 },
        '2024': { totalKm: 1, totalRuns: 1, totalHours: 1 },
        '2025': { totalKm: 1, totalRuns: 1, totalHours: 1 },
      } },
    ]);
    expect(defaultYoyYears(months)).toEqual([2023, 2024, 2025]);
    expect(DEFAULT_YOY_YEAR_COUNT).toBe(3);
  });

  it('returns all years when only 2 exist', () => {
    const months = parseYearOverYear([
      { month: 1, monthLabel: 'Jan', years: {
        '2025': { totalKm: 1, totalRuns: 1, totalHours: 1 },
        '2026': { totalKm: 1, totalRuns: 1, totalHours: 1 },
      } },
    ]);
    expect(defaultYoyYears(months)).toEqual([2025, 2026]);
  });
});

describe('buildYoySeries', () => {
  it('produces exactly 12 entries per year with 0 for absent months', () => {
    const months = parseYearOverYear([
      { month: 3, monthLabel: 'Mar', years: { '2024': { totalKm: 42, totalRuns: 4, totalHours: 4 } } },
    ]);
    const series = buildYoySeries(months, [2024]);
    expect(series).toHaveLength(1);
    expect(series[0].km).toHaveLength(12);
    expect(series[0].runs).toHaveLength(12);
    expect(series[0].km[2]).toBe(42); // March is index 2
    expect(series[0].runs[2]).toBe(4);
    expect(series[0].km[0]).toBe(0); // January absent -> 0
  });

  it('reads the right value at the right index from the live file', () => {
    const months = parseYearOverYear(yearOverYearLive);
    const years = listYoyYears(months);
    const someYear = years[years.length - 1];
    const series = buildYoySeries(months, [someYear]);
    const janEntry = months.find((m) => m.month === 1);
    const expectedJanKm = janEntry?.years[String(someYear)]?.totalKm ?? 0;
    expect(series[0].km[0]).toBe(expectedJanKm);
  });
});

describe('toggleYoyYear', () => {
  const available = [2023, 2024, 2025, 2026];

  it('adds a year', () => {
    expect(toggleYoyYear([2024, 2025], 2023, available)).toEqual([2023, 2024, 2025]);
  });

  it('removes a year', () => {
    expect(toggleYoyYear([2023, 2024, 2025], 2024, available)).toEqual([2023, 2025]);
  });

  it('ignores a year not in available', () => {
    expect(toggleYoyYear([2024, 2025], 1999, available)).toEqual([2024, 2025]);
  });

  it('never returns an empty selection (removing the last remaining year is a no-op)', () => {
    expect(toggleYoyYear([2024], 2024, available)).toEqual([2024]);
  });
});
