/**
 * Compute step for the per-shoe gear aggregate (TREND-05, D-17/D-18/D-19).
 *
 * Reads the published dashboard index (`data/dashboard/index.json`) —
 * produced by `compute-dashboard-index`, which must run first — and writes
 * the gitignored `data/stats/gear-aggregate.json` the Trends Gear tab
 * charts and table read.
 */

import * as path from 'path';

import type { DashboardIndexDocument } from './dashboard-index.types.js';
import type { GearAggregateDocument } from './gear-aggregate.types.js';
import { GEAR_AGGREGATE_SCHEMA_VERSION } from './gear-aggregate.types.js';
import { buildGearAggregate, buildGearCoverage } from './gear-aggregate-logic.js';
import { FileStore } from '../storage/file-store.js';

/** Options for `computeGearAggregate`, defaulted to the repo's standard data layout. */
export interface ComputeGearAggregateOptions {
  indexPath?: string;
  outDir?: string;
}

/**
 * Reads the dashboard index (required — throws with a message naming
 * `compute-dashboard-index` as the prerequisite, mirroring how
 * `compute-dashboard-index` itself throws on a missing manifest), runs the
 * two pure grouping functions, and writes `<outDir>/gear-aggregate.json`.
 * Returns the document as well as writing it, so tests can assert without
 * re-reading the file.
 */
export async function computeGearAggregate(
  options: ComputeGearAggregateOptions = {}
): Promise<GearAggregateDocument> {
  const indexPath = options.indexPath || 'data/dashboard/index.json';
  const outDir = options.outDir || 'data/stats';

  const fileStore = new FileStore('.');

  console.log(`Computing gear aggregate from index: ${indexPath}`);

  let index: DashboardIndexDocument;
  try {
    index = await fileStore.readJson<DashboardIndexDocument>(indexPath);
  } catch (error) {
    throw new Error(
      `Could not read dashboard index at ${indexPath} (${(error as Error).message}); ` +
        `run compute-dashboard-index first.`
    );
  }

  const rows = index.activities;
  const shoes = buildGearAggregate(rows);
  const { totals, byYear } = buildGearCoverage(rows);

  const doc: GearAggregateDocument = {
    schemaVersion: GEAR_AGGREGATE_SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    note:
      'Derived, gitignored, and regenerated by `node dist/index.js compute-gear-aggregate`. ' +
      'Consumers read this file rather than recomputing.',
    totals,
    byYear,
    shoes,
  };

  await fileStore.writeJson(path.join(outDir, 'gear-aggregate.json'), doc);

  console.log(
    `\nGenerated gear aggregate: ${totals.distinctShoes} distinct shoe(s), ` +
      `${totals.percentWithGear}% overall coverage.`
  );
  console.log(`Output written to: ${path.join(outDir, 'gear-aggregate.json')}`);

  return doc;
}
