/**
 * Cross-references the best-efforts document, the committed WMA age-grading
 * factor tables, and the private athlete config to emit per-ranking and
 * per-activity age-grade percentages (REC-06, D-09, D-10, D-13, D-20).
 *
 * D-20's stated reason for precomputing age-grading is that its inputs are
 * identity data: `birthDate`/`sex` never leave the build machine, only the
 * resulting percentages reach `data/stats/age-grading.json`. This module is
 * where that boundary is actually drawn — see `age-grading.types.ts`'s
 * header for the full rule.
 */

import * as path from 'path';

import type { AgeGradingDocument, AgeGradeEntry } from './age-grading.types.js';
import { AGE_GRADING_SCHEMA_VERSION } from './age-grading.types.js';
import type { BestEffortsDocument } from './best-effort.types.js';
import { TARGET_ORDER } from './best-effort.types.js';
import { ageAtDate, parseWmaFactorTable, resolveAgeGrade } from './wma-factors.js';
import type { WmaFactorTable } from './wma-factors.js';
import { loadAthletePrivateConfig } from './athlete-private.js';
import { FileStore } from '../storage/file-store.js';

/** The exact user-facing copy the Records page renders when age-grading is off (18-UI-SPEC Copywriting Contract, path corrected per plan 18-01's locked deviation). */
const DISABLED_REASON =
  'Age-grading is off — add birthDate and sex to data/private/athlete-private.json to enable it.';

/** Options for `computeAgeGrading`, each defaulted to the repo's standard data layout. */
export interface ComputeAgeGradingOptions {
  statsDir?: string;
  wmaDir?: string;
  athletePrivatePath?: string;
}

function round1(value: number): number {
  return Math.round(value * 10) / 10;
}

/** Rounds an `AgeGradeResult`'s percent for publishing. */
function toAgeGradeEntry(percent: number, derived: boolean): AgeGradeEntry {
  return { agePercent: round1(percent), derived };
}

/**
 * Reads the committed best-efforts document, the committed WMA factor
 * tables, and the (optional) private athlete config; writes
 * `<statsDir>/age-grading.json` and returns the same document.
 */
export async function computeAgeGrading(
  options: ComputeAgeGradingOptions = {}
): Promise<AgeGradingDocument> {
  const statsDir = options.statsDir || 'data/stats';
  const wmaDir = options.wmaDir || 'data/wma';
  const athletePrivatePath = options.athletePrivatePath || 'data/private/athlete-private.json';

  const fileStore = new FileStore('.');

  console.log('Computing age-grading percentages...');

  // REQUIRED — without the best-efforts document there is nothing to grade.
  let bestEfforts: BestEffortsDocument;
  try {
    bestEfforts = await fileStore.readJson<BestEffortsDocument>(
      path.join(statsDir, 'best-efforts.json')
    );
  } catch (error) {
    throw new Error(
      `Could not read best-efforts document at ${path.join(statsDir, 'best-efforts.json')} ` +
        `(${(error as Error).message}); run \`compute-best-efforts\` first.`
    );
  }

  // REQUIRED — these are committed files, so their absence is a genuine
  // repository defect, not a degraded state.
  let road: WmaFactorTable;
  let track: WmaFactorTable;
  try {
    const roadRaw = await fileStore.readJson<unknown>(path.join(wmaDir, 'road-factors.json'));
    const parsedRoad = parseWmaFactorTable(roadRaw);
    if (parsedRoad === null) {
      throw new Error(`${path.join(wmaDir, 'road-factors.json')} failed validation`);
    }
    road = parsedRoad;

    const trackRaw = await fileStore.readJson<unknown>(path.join(wmaDir, 'track-factors.json'));
    const parsedTrack = parseWmaFactorTable(trackRaw);
    if (parsedTrack === null) {
      throw new Error(`${path.join(wmaDir, 'track-factors.json')} failed validation`);
    }
    track = parsedTrack;
  } catch (error) {
    throw new Error(
      `Could not load committed WMA factor tables from ${wmaDir} (${(error as Error).message}); ` +
        `these are committed repository files — regenerate them with \`scripts/convert-wma-tables.mjs\` ` +
        `or restore them from git.`
    );
  }

  // OPTIONAL — degrade to a disabled document on any failure. Never throws.
  const privateConfig = await loadAthletePrivateConfig(fileStore, athletePrivatePath);

  if (privateConfig === null) {
    const doc: AgeGradingDocument = {
      schemaVersion: AGE_GRADING_SCHEMA_VERSION,
      generatedAt: new Date().toISOString(),
      note:
        'Derived, gitignored, and regenerated by `node dist/index.js compute-age-grading`. ' +
        'Consumers read this file rather than recomputing.',
      enabled: false,
      disabledReason: DISABLED_REASON,
      editions: { road: road.edition, track: track.edition },
      rankings: {},
      activities: {},
    };
    await fileStore.writeJson(path.join(statsDir, 'age-grading.json'), doc);
    console.log(`\nAge-grading disabled: ${DISABLED_REASON}`);
    return doc;
  }

  const { birthDate, sex } = privateConfig;

  let nullGrades = 0;
  const rankingsPerDistance: Record<string, number> = {};

  const rankings: AgeGradingDocument['rankings'] = {};
  for (const distance of TARGET_ORDER) {
    const entries = bestEfforts.rankings[distance] ?? [];
    const graded: (AgeGradeEntry & { rank: number; activityId: string })[] = [];
    for (const entry of entries) {
      const age = ageAtDate(birthDate, entry.startDate);
      if (age === null) {
        nullGrades++;
        continue;
      }
      const result = resolveAgeGrade(road, track, sex, distance, age, entry.durationSec);
      if (result === null) {
        nullGrades++;
        continue;
      }
      graded.push({
        rank: entry.rank,
        activityId: entry.activityId,
        ...toAgeGradeEntry(result.percent, result.derived),
      });
    }
    rankings[distance] = graded;
    rankingsPerDistance[distance] = graded.length;
  }

  const activities: AgeGradingDocument['activities'] = {};
  for (const [activityId, activityEfforts] of Object.entries(bestEfforts.activities)) {
    const byDistance: Partial<Record<(typeof TARGET_ORDER)[number], AgeGradeEntry>> = {};
    for (const effort of activityEfforts.efforts) {
      const age = ageAtDate(birthDate, activityEfforts.startDate);
      if (age === null) {
        nullGrades++;
        continue;
      }
      const result = resolveAgeGrade(road, track, sex, effort.distance, age, effort.durationSec);
      if (result === null) {
        nullGrades++;
        continue;
      }
      byDistance[effort.distance] = toAgeGradeEntry(result.percent, result.derived);
    }
    activities[activityId] = byDistance;
  }

  const doc: AgeGradingDocument = {
    schemaVersion: AGE_GRADING_SCHEMA_VERSION,
    generatedAt: new Date().toISOString(),
    note:
      'Derived, gitignored, and regenerated by `node dist/index.js compute-age-grading`. ' +
      'Consumers read this file rather than recomputing.',
    enabled: true,
    disabledReason: null,
    editions: { road: road.edition, track: track.edition },
    rankings,
    activities,
  };

  await fileStore.writeJson(path.join(statsDir, 'age-grading.json'), doc);

  console.log('\nAge-grading enabled:');
  for (const distance of TARGET_ORDER) {
    console.log(`- ${distance}: ${rankingsPerDistance[distance]} ranking entries graded`);
  }
  console.log(`- ${Object.keys(activities).length} activities graded`);
  console.log(`- ${nullGrades} resolveAgeGrade calls returned null (omitted)`);

  return doc;
}
